### PR TITLE
fixed bugs in handling market orders

### PR DESCRIPTION
**Pull request by ghost**
This patch fixes a bug that plham.Market ignores market orders if there is no corresponding limit order.

### CODE REVIEW

**Comment by masanorihirano** [comment]
Have you considered the `queue` in `Orderbook` class?
https://github.com/plham/plhamJ/blob/284e0916f651a624970130e9de5edd7b74a9f69a/plham/OrderBook.java#L222

The current modification seems to have potential troubles.
When market order and limit order in either sell or buy order book, this modification seems to return incorrect best price.

I agree with this bug fix is necessary and the bug is rare but critical.
However, we should check many potential conflicts with this bug fix.

**Comment by ghost** [comment]
> When market order and limit order in either sell or buy order book, this modification seems to return incorrect best price.

Yes, it should return some problematic results.
I think we have several ways of implementation to deal with this problem.
 1. force to set enough "good" price automatically when plham creates a market order instance
 1. add some conditional branch to make Order#getPrice() return enough "good" price
 1. refactor the Order class to make BuyMarketOrder, BuyLimitOrder, SellMarketOrder and SellLimitOrder classes to make Order#getPrice() return enough "good" price
Which way do you think is better? I think the first one is better to minimize the modification.

**Comment by masanorihirano** [comment]
I also think the first option is best. Usually, when there are both buy and sell market orders on the market, these orders cannot be executed by itself. So, to execute any market order, the corresponding limit order is necessary. Thus, the best price should be set to the "best price among limit order."

**Comment by masanorihirano** [comment]
Moreover, if you make this modification, you should also implement to:

https://github.com/plham/plhamJ/blob/284e0916f651a624970130e9de5edd7b74a9f69a/plham/Market.java#L559

It is not coherent that a market accepts market orders without the corresponding limit orders only when the market is open.

**Comment by masanorihirano** [comment]
This comment was wrong. 
97bb9ff can cover also the issue in this comment.
Please never mind.

> Moreover, if you make this modification, you should also implement to:
> 
> https://github.com/plham/plhamJ/blob/284e0916f651a624970130e9de5edd7b74a9f69a/plham/Market.java#L559
> 
> It is not coherent that a market accepts market orders without the corresponding limit orders only when the market is open.

**Comment by ghost** [comment]
> Thus, the best price should be set to the "best price among limit order."

It's too complex to implement, as it needs orderbook information to calculate order's price.
I think setting price 1 for sell orders and 1e9 (or some large number) for buy orders is enough.

**Comment by masanorihirano** [comment]
After deep consideration, I suggest that markets return Nan as the best price when the best order is a market order.

**Comment by ghost** [comment]
Sounds good. Fixed according to your suggestion.

**Comment by masanorihirano** [comment]
By the way, how do you think this:

https://github.com/plham/plhamJ/blob/284e0916f651a624970130e9de5edd7b74a9f69a/plham/Order.java#L71

This assertion is not suitable for a market order.

**Comment by masanorihirano** [comment]
How do you think whether this processing order is preferable or not?

https://github.com/plham/plhamJ/blob/9cf542ccb9d57a49539e63f21a09d06c8f1e384b/plham/Order.java#L71

https://github.com/plham/plhamJ/blob/9cf542ccb9d57a49539e63f21a09d06c8f1e384b/plham/Order.java#L82

I think price overwriting should be placed before assertion.

**Comment by masanorihirano** [comment]
About `remainExecutableOrders` in `Itayose` class, is it correctly working when there are only sell and buy market orders? If there are, this method returns `True`. However, this situation is not executable.

**Comment by masanorihirano** [comment]
The problem mentioned in the previous comments is also affecting:

https://github.com/plham/plhamJ/blob/c56d5a965481b8fa86a1856c9cac13bb183fea79/plham/util/Itayose.java#L153

https://github.com/plham/plhamJ/blob/c56d5a965481b8fa86a1856c9cac13bb183fea79/plham/util/Itayose.java#L154

If there are only both sell and buy market orders on the market, both `lastSellPrice` and `lastBuyPrice` are Nan. It could cause some errors.

As you know, this situation hit the assertion:

https://github.com/plham/plhamJ/blob/c56d5a965481b8fa86a1856c9cac13bb183fea79/plham/util/Itayose.java#L156

However, if you fix `remainExecutableOrders`, these problems are avoidable because both `lastSellPrice` and `lastBuyPrice` are 0.0.

**Comment by masanorihirano** [comment]
Last comment: Why have you dropped the following line in d539d672cf7f24ce42d2ae23c8425aacce7ccde0 :
```
System.out.println("# Itayose exchangePrice " + exchangePrice);
```

**Comment by ghost** [comment]
> I think price overwriting should be placed before assertion.

It's not good because the comparison between 0 and NaN result in false.

**Comment by ghost** [comment]
Thank you for fixing indents. I might ought to place modeline comments.

**Comment by ghost** [comment]
> About remainExecutableOrders in Itayose class, is it correctly working when there are only sell and buy market orders? If there are, this method returns True. However, this situation is not executable.
> If there are only both sell and buy market orders on the market, both lastSellPrice and lastBuyPrice are Nan. It could cause some errors.

Yeah, it should be handled by remainExecutableOrders.

**Comment by ghost** [comment]
NO, IT'S NOT. 

Sorry, I've just got up. My head is not working well.
Because it does itayose, a pair of buy and sell market orders is executable.

https://github.com/plham/plhamJ/blob/c56d5a965481b8fa86a1856c9cac13bb183fea79/plham/util/Itayose.java#L156
The assertion hits only if there are no limit orders in the both sides.

**Comment by ghost** [comment]
> Why have you dropped the following line in d539d67 :

Ah, you need it?
The reason why I dropped the line is that I thought it was for just debugging, and it's too annoying when you use the method many times.

I'll make an another pull-req for this.

**Comment by masanorihirano** [comment]
At first, I suggest that we change

https://github.com/plham/plhamJ/blob/9cf542ccb9d57a49539e63f21a09d06c8f1e384b/plham/Order.java#L71

https://github.com/plham/plhamJ/blob/9cf542ccb9d57a49539e63f21a09d06c8f1e384b/plham/Order.java#L82

to
```
if (this.kind == KIND_BUY_MARKET_ORDER || this.kind == KIND_SELL_MARKET_ORDER) {
	this.price = Double.NaN;
} else {
	assert price >= 0.0 : "price >= 0.0";
	this.price = price;
}
```

How do you think?


Secondary, about `remainExecutableOrders`, I think you should not use the assertion:

https://github.com/plham/plhamJ/blob/c56d5a965481b8fa86a1856c9cac13bb183fea79/plham/util/Itayose.java#L156

The situation that there are no limit orders and both sell and buy market orders is not executable but also not errant.
Even if there are only market orders before itayose, it will be correctly working if additional limit order coming after the first itayose. So, when a simulation faces the situation, the assertion should not be run.

**Comment by ghost** [comment]
>  I suggest that we change

Got it. It looks good.

> Even if there are only market orders before itayose, it will be correctly working if additional limit order coming after the first itayose. So, when a simulation faces the situation, the assertion should not be run.

OK. But I believe that the situation is erroneous in many situation.
The situation that there are no limit orders but market orders is strange and in many cases, it will be an error(not in plham, but in the user's code) , so the user should be noticed.
I will replace assertion to some warning message.

**Comment by masanorihirano** [comment]
Your modifications seem far enough. However, I think the warning is meaningless. It is because the current code will make bugs when there are only market orders. Executed between sell and buy market order, the market does not have execution price. It causes an additional error in the process of money transactions among agents. So, I think, when there are only market orders, the market should not be executed. Thus, I suggest the following modification:

```
	public static boolean remainExecutableOrders(Market market) {
		if (market.getBuyOrderBook().size() == 0) return false;
		if (market.getSellOrderBook().size() == 0) return false;
		Order buy = market.getBuyOrderBook().getBestOrder();
		Order sell = market.getSellOrderBook().getBestOrder();
		if (!buy.isMarketOrder() && !sell.isMarketOrder()) return buy.price >= sell.price;
		if (buy.isMarketOrder() && !sell.isMarketOrder()) return true;
		if (!buy.isMarketOrder() && sell.isMarketOrder()) return true;

		for (Order order: market.getBuyOrderBook().queue){
			if (!order.isMarketOrder()){
				return true;
			}
		}
		for (Order order: market.getSellOrderBook().queue){
			if (!order.isMarketOrder()){
				return true;
			}
		}
		return false;
	}
```

**Comment by masanorihirano** [comment]
Although we discuss the modification a lot above, an opening market is also not working when there are only market orders and new orders coming. So, your modification was far enough. Thus, you can ignore my last comments.

**Review by masanorihirano — APPROVED** [review]

**Pull request merged**
